### ISSUE TITLE
Invalid constructor code 388FA391 error when trying to use GetDialog 

### ISSUE THREAD

**Issue by amirgolshan** [steavy29/Telegram.Net#26]
I want to get a chat by its name and send message to the chat.
My code is as below:

            int id = 0;
            var client = await InitializeAndAuthenticateClient();
            var chatlist = await client.GetDialogs(0, 10, 0) as MessagesDialogsConstructor;
            foreach (Chat A in chatlist.chats)
            {

                var chatreq = A as ChatConstructor;

                if (chatreq.title == "chatname")
                {
                    id= chatreq.id;
                    break;
                }

             }

            if(id!=0)
            {

                await client.SendChatMessage(id, "hello");

            }

but I get this error: "Invalid constructor code 388FA391 " .
How can I fix this? Or any other suggestion to get the chat id?
Thanks.

**Comment by steavy29** [comment]
Hi. Which line of code throws the exception?

**Comment by amirgolshan** [comment]
Hi,
The full stack trace:
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 341
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.MTProto.MessageMediaVideoConstructor.Read(BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 3923
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 351
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.MTProto.MessageForwardedConstructor.Read(BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 3779
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 351
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.MTProto.TLObject.<>c__DisplayClass13_0`1.<ReadVector>b__0() in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 360
   at Telegram.Net.Core.MTProto.TLObject.ReadVector[T](BinaryReader reader, Func`1 readNextFunc, Boolean readVectorDataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 380
   at Telegram.Net.Core.MTProto.TLObject.ReadVector[T](BinaryReader reader, Boolean readVectorDataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 360
   at Telegram.Net.Core.MTProto.MessagesDialogsSliceConstructor.Read(BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 6217
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 351
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.Requests.GetDialogsRequest.OnResponse(BinaryReader reader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\Requests\GetDialogsRequest.cs:line 34
   at Telegram.Net.Core.Network.MtProtoSender.HandleRpcResult(BinaryReader messageReader) in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\Network\MtProtoSender.cs:line 372
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Telegram.Net.Core.Network.MtProtoSender.<Send>d__25.MoveNext() in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\Network\MtProtoSender.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Telegram.Net.Core.TelegramClient.<SendRpcRequest>d__24.MoveNext() in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\TelegramClient.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Telegram.Net.Core.TelegramClient.<GetDialogs>d__45.MoveNext() in D:\golshan\tlsharp\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\TelegramClient.cs:line 476
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Telegram.Net.Tests.Tests.<findchat>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at advernew.Form1.<button2_Click>d__3.MoveNext()

**Comment by steavy29** [comment]
Hi. Fixed. Could you please check if it's resolved for you now?

**Comment by steavy29** [comment]
Please, create new issue if the problem still reproduces for you.
