### ISSUE TITLE
GetDialogs new error:Invalid constructor code 6D2F6F65

### ISSUE THREAD

**Issue by amirgolshan** [steavy29/Telegram.Net#29]
Hi ,
I got the same error(issues #26) after using the fixed code :(with different constructor code error)
"Invalid constructor code 6D2F6F65"

and the top stack trace:
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 341
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.MTProto.VideoConstructor.Read(BinaryReader reader) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 4672
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader, UInt32 dataCode) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 351
   at Telegram.Net.Core.MTProto.TLObject.Read[T](BinaryReader reader) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 320
   at Telegram.Net.Core.MTProto.MessageMediaVideoConstructor.Read(BinaryReader reader) in D:\golshan\tlsharp\telegramnew\Telegram.Net-master\Telegram.Net-master\Telegram.Net.Core\MTProto\TLObject.cs:line 3923
........................
Best.

**Comment by steavy29** [comment]
Hi, that's weird, I can't find this constructor code neither in Telegram.Net sources nor in the documentation, not even in the latest 65 API version schema. Do you have any thoughts on which object it might describe?

**Comment by amirgolshan** [comment]
Hi,
You're right I could not find any data either.
Just It seems that the code can not parse the messages. The code passes the dialog read procedure and get stuck in reading the vector of messages.
Have you ever tried the GETDIALOG function?
May be I'm using in a wrong way.
Best

**Comment by steavy29** [comment]
Yes, I tried. But the thing is that it really depends on what content do you have in your messages. I've tried with text messages, photos, pictures and stickers. What content do you have in your dialogs?

**Comment by amirgolshan** [comment]
I have the same content as you mentioned.
I just need to find the chat so Is it possible to ignore the messages content parsing and just look for the chats vector?

**Comment by steavy29** [comment]
Can we move to telegram chat, I have an idea how to reproduce this for me? Please add me there: https://t.me/steavy29
